### ISSUE TITLE
NPE in SpeakerImageProvider

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX#642]
### Expected Behavior
No NPE is thrown

### Current Behavior
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
at org.tweetwallfx.devoxx.cfp.stepengine.dataprovider.SpeakerImageProvider.getSpeakerImage(SpeakerImageProvider.java:53)
at org.tweetwallfx.devoxx18be.steps.Devoxx18ShowTopRatedWeek.createTalkNode(Devoxx18ShowTopRatedWeek.java:118)
at org.tweetwallfx.devoxx18be.steps.Devoxx18ShowTopRatedWeek.doStep(Devoxx18ShowTopRatedWeek.java:87)
at org.tweetwallfx.stepengine.api.StepEngine.lambda$process$12(StepEngine.java:197)
at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
at java.security.AccessController.doPrivileged(Native Method)
at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by mklaehn** [comment]
Configuration error.
cinema wall project fixated the talkID to one not available in current Event CFP API. This made it impossible to retrieve the a Speaker based on his/her name and thus the Speaker field in SessionData was null. SpeakerImageDataProvider expects (among other things) a non-null Speaker object.
