### ISSUE TITLE
TopTalksDataProvider not available (although configured)

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX#644]
### Expected Behavior
Configured DataProvider should be available.

### Current Behavior
```
Exception in thread "engine" java.lang.IllegalStateException: A DataProvider of type 'org.tweetwallfx.devoxx.cfp.stepengine.dataprovider.TopTalksTodayDataProvider' is currently not been available.
	at org.tweetwallfx.stepengine.api.StepEngine$MachineContext.lambda$getDataProvider$0(StepEngine.java:206)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.tweetwallfx.stepengine.api.StepEngine$MachineContext.getDataProvider(StepEngine.java:206)
	at org.tweetwallfx.devoxx18be.steps.Devoxx18FlipOutScheduleToday.shouldSkip(Devoxx18FlipOutScheduleToday.java:64)
	at org.tweetwallfx.stepengine.api.StepEngine.process(StepEngine.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
### Context
Maybe a race condition (threading issue?)

**Comment by svenreimers** [comment]
Reason for this problem is that during shouldSkip the new restrictions should already be in place.
The actual sequence is:
```
            Step step = stepIterator.next();
            while (step.shouldSkip(context)) {
                LOG.info("Skip step: {}", step.getClass().getSimpleName());
                step = stepIterator.next();
            }
```
and later on
`context.restrictAvailableDataProviders(stepIterator.getRequiredDataProviders(stepToExecute));`
so that in `shouldSkip` the dataProviders for this step are not yet visible for the step.
